---
- name: Install Apache
  apt: name=apache2 state=present

- name: Install php 7.0
  apt: name=libapache2-mod-php7.0 state=present

- name: Start Apache
  service: name=apache2 state=started enabled=yes

- name: Install Hello World PHP script
  copy: src=info.php dest=/var/www/html/info.php mode=0664

- name: Restart Apache
  service: name=apache2 state=restarted

